hostname := "MacBookPro@Ones"

deploy:
  nix build .#darwinConfigurations.{{hostname}}.system \
        --extra-experimental-features 'nix-command flakes'
  ./result/sw/bin/darwin-rebuild switch --flake .#{{hostname}}

